/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CollectorRouteImport } from './routes/collector'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectorIndexRouteImport } from './routes/collector.index'
import { Route as CitizenIndexRouteImport } from './routes/citizen.index'
import { Route as CollectorTasksRouteImport } from './routes/collector.tasks'
import { Route as CollectorScheduleRouteImport } from './routes/collector.schedule'
import { Route as CollectorMapRouteImport } from './routes/collector.map'
import { Route as CollectorHistoryRouteImport } from './routes/collector.history'
import { Route as CitizenScheduleRouteImport } from './routes/citizen.schedule'
import { Route as CitizenReportsRouteImport } from './routes/citizen.reports'
import { Route as CitizenNotificationsRouteImport } from './routes/citizen.notifications'
import { Route as CitizenNewRouteImport } from './routes/citizen.new'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorRoute = CollectorRouteImport.update({
  id: '/collector',
  path: '/collector',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorIndexRoute = CollectorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectorRoute,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitizenRoute,
} as any)
const CollectorTasksRoute = CollectorTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorScheduleRoute = CollectorScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorMapRoute = CollectorMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorHistoryRoute = CollectorHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CollectorRoute,
} as any)
const CitizenScheduleRoute = CitizenScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenReportsRoute = CitizenReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenNotificationsRoute = CitizenNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenNewRoute = CitizenNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CitizenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRouteWithChildren
  '/collector': typeof CollectorRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/citizen/new': typeof CitizenNewRoute
  '/citizen/notifications': typeof CitizenNotificationsRoute
  '/citizen/reports': typeof CitizenReportsRoute
  '/citizen/schedule': typeof CitizenScheduleRoute
  '/collector/history': typeof CollectorHistoryRoute
  '/collector/map': typeof CollectorMapRoute
  '/collector/schedule': typeof CollectorScheduleRoute
  '/collector/tasks': typeof CollectorTasksRoute
  '/citizen/': typeof CitizenIndexRoute
  '/collector/': typeof CollectorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/citizen/new': typeof CitizenNewRoute
  '/citizen/notifications': typeof CitizenNotificationsRoute
  '/citizen/reports': typeof CitizenReportsRoute
  '/citizen/schedule': typeof CitizenScheduleRoute
  '/collector/history': typeof CollectorHistoryRoute
  '/collector/map': typeof CollectorMapRoute
  '/collector/schedule': typeof CollectorScheduleRoute
  '/collector/tasks': typeof CollectorTasksRoute
  '/citizen': typeof CitizenIndexRoute
  '/collector': typeof CollectorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRouteWithChildren
  '/collector': typeof CollectorRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/citizen/new': typeof CitizenNewRoute
  '/citizen/notifications': typeof CitizenNotificationsRoute
  '/citizen/reports': typeof CitizenReportsRoute
  '/citizen/schedule': typeof CitizenScheduleRoute
  '/collector/history': typeof CollectorHistoryRoute
  '/collector/map': typeof CollectorMapRoute
  '/collector/schedule': typeof CollectorScheduleRoute
  '/collector/tasks': typeof CollectorTasksRoute
  '/citizen/': typeof CitizenIndexRoute
  '/collector/': typeof CollectorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/citizen'
    | '/collector'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/citizen/new'
    | '/citizen/notifications'
    | '/citizen/reports'
    | '/citizen/schedule'
    | '/collector/history'
    | '/collector/map'
    | '/collector/schedule'
    | '/collector/tasks'
    | '/citizen/'
    | '/collector/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/citizen/new'
    | '/citizen/notifications'
    | '/citizen/reports'
    | '/citizen/schedule'
    | '/collector/history'
    | '/collector/map'
    | '/collector/schedule'
    | '/collector/tasks'
    | '/citizen'
    | '/collector'
  id:
    | '__root__'
    | '/'
    | '/citizen'
    | '/collector'
    | '/login'
    | '/signup'
    | '/unauthorized'
    | '/citizen/new'
    | '/citizen/notifications'
    | '/citizen/reports'
    | '/citizen/schedule'
    | '/collector/history'
    | '/collector/map'
    | '/collector/schedule'
    | '/collector/tasks'
    | '/citizen/'
    | '/collector/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitizenRoute: typeof CitizenRouteWithChildren
  CollectorRoute: typeof CollectorRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector': {
      id: '/collector'
      path: '/collector'
      fullPath: '/collector'
      preLoaderRoute: typeof CollectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector/': {
      id: '/collector/'
      path: '/'
      fullPath: '/collector/'
      preLoaderRoute: typeof CollectorIndexRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/collector/tasks': {
      id: '/collector/tasks'
      path: '/tasks'
      fullPath: '/collector/tasks'
      preLoaderRoute: typeof CollectorTasksRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/schedule': {
      id: '/collector/schedule'
      path: '/schedule'
      fullPath: '/collector/schedule'
      preLoaderRoute: typeof CollectorScheduleRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/map': {
      id: '/collector/map'
      path: '/map'
      fullPath: '/collector/map'
      preLoaderRoute: typeof CollectorMapRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/history': {
      id: '/collector/history'
      path: '/history'
      fullPath: '/collector/history'
      preLoaderRoute: typeof CollectorHistoryRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/citizen/schedule': {
      id: '/citizen/schedule'
      path: '/schedule'
      fullPath: '/citizen/schedule'
      preLoaderRoute: typeof CitizenScheduleRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/reports': {
      id: '/citizen/reports'
      path: '/reports'
      fullPath: '/citizen/reports'
      preLoaderRoute: typeof CitizenReportsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/notifications': {
      id: '/citizen/notifications'
      path: '/notifications'
      fullPath: '/citizen/notifications'
      preLoaderRoute: typeof CitizenNotificationsRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/new': {
      id: '/citizen/new'
      path: '/new'
      fullPath: '/citizen/new'
      preLoaderRoute: typeof CitizenNewRouteImport
      parentRoute: typeof CitizenRoute
    }
  }
}

interface CitizenRouteChildren {
  CitizenNewRoute: typeof CitizenNewRoute
  CitizenNotificationsRoute: typeof CitizenNotificationsRoute
  CitizenReportsRoute: typeof CitizenReportsRoute
  CitizenScheduleRoute: typeof CitizenScheduleRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
}

const CitizenRouteChildren: CitizenRouteChildren = {
  CitizenNewRoute: CitizenNewRoute,
  CitizenNotificationsRoute: CitizenNotificationsRoute,
  CitizenReportsRoute: CitizenReportsRoute,
  CitizenScheduleRoute: CitizenScheduleRoute,
  CitizenIndexRoute: CitizenIndexRoute,
}

const CitizenRouteWithChildren =
  CitizenRoute._addFileChildren(CitizenRouteChildren)

interface CollectorRouteChildren {
  CollectorHistoryRoute: typeof CollectorHistoryRoute
  CollectorMapRoute: typeof CollectorMapRoute
  CollectorScheduleRoute: typeof CollectorScheduleRoute
  CollectorTasksRoute: typeof CollectorTasksRoute
  CollectorIndexRoute: typeof CollectorIndexRoute
}

const CollectorRouteChildren: CollectorRouteChildren = {
  CollectorHistoryRoute: CollectorHistoryRoute,
  CollectorMapRoute: CollectorMapRoute,
  CollectorScheduleRoute: CollectorScheduleRoute,
  CollectorTasksRoute: CollectorTasksRoute,
  CollectorIndexRoute: CollectorIndexRoute,
}

const CollectorRouteWithChildren = CollectorRoute._addFileChildren(
  CollectorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitizenRoute: CitizenRouteWithChildren,
  CollectorRoute: CollectorRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
